# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 434)
        Form.setMinimumSize(QtCore.QSize(574, 434))
        Form.setMaximumSize(QtCore.QSize(574, 434))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 621, 461))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-6, 0, 621, 451))
        self.label.setStyleSheet("border-image: url(:/image/background.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 330, 91, 31))
        self.pushButton_6.setStyleSheet(".QPushButton{\n"
"background-color: rgb(202, 87, 242);\n"
"font: 16pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(202, 87, 242);\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: rgb(255, 170, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(340, 330, 91, 31))
        self.pushButton_7.setStyleSheet(".QPushButton{\n"
"background-color: rgb(202, 87, 242);\n"
"font: 8pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(202, 87, 242);\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: rgb(255, 170, 255);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(100, 120, 391, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_6.setText(_translate("Form", "Menu"))
        self.pushButton_7.setText(_translate("Form", "Performance"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Start Time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Stop Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Duration (second)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Q1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Q2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Q3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Q4"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Q5"))
import res_rc
