# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gaming.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 434)
        Form.setMinimumSize(QtCore.QSize(574, 434))
        Form.setMaximumSize(QtCore.QSize(574, 434))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 621, 461))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-6, 0, 621, 451))
        self.label.setStyleSheet("border-image: url(:/image/background.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(100, 100, 71, 51))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("font: 75 22pt \"Times New Roman\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(210, 140, 161, 51))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("font: 75 22pt \"Times New Roman\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 210, 91, 31))
        self.pushButton_2.setStyleSheet(".QPushButton{\n"
"background-color: rgb(196, 196, 196);\n"
"font: 18pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(196, 196, 196);;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 210, 91, 31))
        self.pushButton_3.setStyleSheet(".QPushButton{\n"
"background-color: rgb(196, 196, 196);\n"
"font: 18pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(196, 196, 196);;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 210, 91, 31))
        self.pushButton_4.setStyleSheet(".QPushButton{\n"
"background-color: rgb(196, 196, 196);\n"
"font: 18pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(196, 196, 196);;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: white;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(170, 260, 251, 41))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"border-radius: 18px;\n"
"background-color: green;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(250, 320, 91, 31))
        self.pushButton_5.setStyleSheet(".QPushButton{\n"
"background-color: rgb(202, 87, 242);\n"
"font: 18pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(202, 87, 242);\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: rgb(255, 170, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(370, 290, 201, 141))
        self.label_3.setStyleSheet("border-image: url(:/image_2/bear.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Q1:"))
        self.label_6.setText(_translate("Form", "5 * 6 = ?"))
        self.pushButton_2.setText(_translate("Form", "30"))
        self.pushButton_3.setText(_translate("Form", "18"))
        self.pushButton_4.setText(_translate("Form", "27"))
        self.label_7.setText(_translate("Form", "Comment"))
        self.pushButton_5.setText(_translate("Form", "Next"))
import res_rc
