# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 800, 600))
        self.widget.setMinimumSize(QtCore.QSize(800, 600))
        self.widget.setMaximumSize(QtCore.QSize(800, 600))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-6, 0, 800, 600))
        self.label.setMinimumSize(QtCore.QSize(800, 600))
        self.label.setMaximumSize(QtCore.QSize(800, 600))
        self.label.setStyleSheet("border-image: url(:/image/background.jpg)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(230, 190, 331, 51))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("font: 16pt \"Cooper Black\";\n"
"background-color: rgb(85, 170, 255, 200);\n"
"border-radius: 20px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(320, 310, 151, 71))
        self.pushButton.setStyleSheet(".QPushButton{\n"
"background-color: rgb(0, 203, 106);\n"
"font: 18pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid #4CAF50;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: #4CAF50;\n"
"  color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(510, 440, 201, 141))
        self.label_3.setStyleSheet("border-image: url(:/image_2/bear.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(260, 440, 401, 41))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("font: 75 8pt \"Segoe Print\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 20, 151, 31))
        self.pushButton_2.setStyleSheet(".QPushButton{\n"
"background-color: rgb(255, 170, 255);\n"
"font: 16pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(255, 156, 254);\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color:rgb(255, 114, 255);\n"
"  color: white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "1`"))
        self.label_2.setText(_translate("Form", "Multiplicaiton Challenges"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.label_4.setText(_translate("Form", "Can you teach me how to do multiplications?"))
        self.pushButton_2.setText(_translate("Form", "Performace"))
import res_rc
