# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'summary.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(574, 434)
        Form.setMinimumSize(QtCore.QSize(574, 434))
        Form.setMaximumSize(QtCore.QSize(574, 434))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 621, 461))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(-6, 0, 621, 451))
        self.label.setStyleSheet("border-image: url(:/image/background.jpg)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(210, 140, 161, 51))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("font: 75 22pt \"Times New Roman\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(240, 180, 101, 51))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("font: 75 22pt \"Times New Roman\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(150, 230, 281, 41))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("font: 18pt \"Sriracha\";\n"
"background-color: rgb(0, 163, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(390, 300, 201, 141))
        self.label_8.setStyleSheet("border-image: url(:/image_2/bear.png)")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 310, 91, 31))
        self.pushButton_6.setStyleSheet(".QPushButton{\n"
"background-color: rgb(202, 87, 242);\n"
"font: 18pt \"Cooper Black\";\n"
"border-radius: 15px;\n"
"color: black; \n"
"border: 2px solid rgb(202, 87, 242);\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: rgb(255, 170, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Your Score:"))
        self.label_7.setText(_translate("Form", "8 / 10"))
        self.label_5.setText(_translate("Form", "Well Done!"))
        self.pushButton_6.setText(_translate("Form", "Menu"))
import res_rc
